export const GAME_CONFIG = {
  canvas: {
    width: 540,
    height: 960,
  },
  storage: {
    bestTimeKey: 'defiende-pipis:best-time',
  },
  loading: {
    minDuration: 900,
  },
  barn: {
    centerX: 270,
    centerY: 592,
    radiusX: 218,
    radiusY: 310,
    fencePadding: 42,
  },
  chicken: {
    radius: 34,
    speedMin: 18,
    speedMax: 42,
    turnIntervalMin: 0.8,
    turnIntervalMax: 2.4,
    animationFrameDuration: 0.18,
  },
  egg: {
    radius: 26,
    hatchRadius: 48,
    duration: 6.5,
    warningTime: 2,
    pulseSpeed: 8,
  },
  fox: {
    radius: 42,
    scareRadius: 68,
    eatRadius: 44,
    spawnMargin: 62,
    fleeDuration: 0.3,
    animationFrameDuration: 0.12,
  },
  difficultyRamp: {
    foxSpawnIntervalReductionPerMinute: 0.62,
    foxSpeedIncreasePerMinute: 0.34,
    eggSpawnDelayIncreasePerMinute: 0.46,
    eggDurationReductionPerMinute: 0.18,
    maxFoxesIncreasePerMinute: 1,
  },
  levels: {
    easy: {
      label: 'Fácil',
      description: 'Más gallinas, menos zorros y margen para respirar.',
      initialChickens: 5,
      foxSpawnInterval: 3.8,
      eggSpawnInterval: 10,
      foxBaseSpeed: 106,
      maxFoxes: 3,
    },
    medium: {
      label: 'Medio',
      description: 'Un corral movido, con zorros entrando a buen ritmo.',
      initialChickens: 4,
      foxSpawnInterval: 2.85,
      eggSpawnInterval: 13.5,
      foxBaseSpeed: 138,
      maxFoxes: 4,
    },
    hard: {
      label: 'Difícil',
      description: 'Pocas gallinas, zorros veloces y casi sin tregua.',
      initialChickens: 3,
      foxSpawnInterval: 1.95,
      eggSpawnInterval: 18,
      foxBaseSpeed: 172,
      maxFoxes: 5,
    },
  },
  effects: {
    scareDuration: 0.36,
    hatchDuration: 0.5,
    dangerPulseDuration: 0.6,
  },
};
